repository:
  name: cla-assistant
  description: Contributor License Agreement assistant (CLA assistant)  
  homepage: https://cla-assistant.io/  
  private: false  
  has_issues: true  
  has_wiki: false  
  has_downloads: true  
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: architecture
    color: 5319e7
  - name: bug
    color: d93f0b
  - name: design
    color: 009800
  - name: feature
    color: 84b6eb
  - name: greenkeeper
    color: 00c775
  - name: help wanted
    color: 006b75
  - name: wontfix
    color: eeeeee
